INSERT INTO Books (book_num, book_name, book_author, book_publisher, book_year, picture_url, rating, description) VALUES 
("111231", "Marianniny rozmary", "Alfred de Musset", "Artur", "2011", "http://www.martinus.sk/data/tovar/_m/111/m111231.jpg", "0", "Jedna z nejznámějších tragikomedií romantického autora je kouzelnou a hravou oslavou lásky, v níž se humor a vtip prolínají s fatálními okolnostmi, jež brání naplnění romantických představ zamilovaných hrdinů.");
INSERT INTO Books (book_num, book_name, book_author, book_publisher, book_year, picture_url, rating, description) VALUES 
("111232", "Probuzení jara", "Frank Wedekind", "Artur", "2011", "http://www.martinus.sk/data/tovar/_m/111/m111232.jpg", "0", "Hra patří mezi nejvýznamnější díla moderního německého divadla. Vzbudila na sklonku 19. stol. značný rozruch a pozornost mezi čtenáři (pro divadelní uvedení ji cenzura nepovolila)...");
INSERT INTO Books (book_num, book_name, book_author, book_publisher, book_year, picture_url, rating, description) VALUES 
("111233", "Wanted", "Sara Shepard", "Atom", "2011", "http://www.martinus.sk/data/tovar/_m/111/m111233.jpg", "0", "In Rosewood, not all that glitters is gold, and the town harbors secrets darker than anyone could imagine—like the truth about what really happened the night Alison DiLaurentis went missing...");
INSERT INTO Books (book_num, book_name, book_author, book_publisher, book_year, picture_url, rating, description) VALUES 
("111234", "Rusko a národy", "Wojciech Zajaczkowski", "Misgurnus", "2011", "http://www.martinus.sk/data/tovar/_m/111/m111234.jpg", "0", "Ještě před sto lety ležela uvnitř ruských hranic část Polska a také Finsko, dnes se v nich nachází Severní Kavkaz a Tatarsán. Nerusové ovšem měli na dějiny této oblasti obrovský vliv.");
INSERT INTO Books (book_num, book_name, book_author, book_publisher, book_year, picture_url, rating, description) VALUES ();
INSERT INTO Books (book_num, book_name, book_author, book_publisher, book_year, picture_url, rating, description) VALUES ();
